# Generated by Django 6.0 on 2025-12-24 18:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("fiscal_year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Framework",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("status_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TKResources",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="FrameworkRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("short_description", models.TextField()),
                ("long_description", models.TextField()),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.framework"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_requirements",
                        to="core.frameworkrequirement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InternalControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("short_description", models.TextField()),
                ("long_description", models.TextField()),
                ("test_procedures", models.TextField()),
                (
                    "wp_ref",
                    models.CharField(
                        max_length=255, verbose_name="Workpaper Reference"
                    ),
                ),
                (
                    "requirements",
                    models.ManyToManyField(
                        related_name="controls", to="core.frameworkrequirement"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tod_result", models.TextField()),
                ("toe_result", models.TextField()),
                (
                    "conclusion",
                    models.CharField(
                        choices=[
                            ("NO_EXC", "No Exceptions Noted"),
                            ("EXC_UNREM", "Exception Noted (Unremediated)"),
                            ("EXC_REM", "Exception Noted (Remediated)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.audit"
                    ),
                ),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.internalcontrol",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.status"
                    ),
                ),
                (
                    "primary_reviewer_so",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_signoffs",
                        to="core.tkresources",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_assessments",
                        to="core.tkresources",
                    ),
                ),
                (
                    "secondary_reviewer_so",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secondary_signoffs",
                        to="core.tkresources",
                    ),
                ),
                (
                    "tester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tested_assessments",
                        to="core.tkresources",
                    ),
                ),
                (
                    "tester_so",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tester_signoffs",
                        to="core.tkresources",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("finding_date", models.DateField()),
                (
                    "finding_category",
                    models.CharField(
                        choices=[
                            ("Finding", "Finding"),
                            ("Observation", "Observation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                ("finding_rca", models.TextField(verbose_name="Root Cause Analysis")),
                (
                    "ca_owner",
                    models.CharField(
                        max_length=255, verbose_name="Corrective Action Owner"
                    ),
                ),
                ("ca_plan", models.TextField()),
                ("ca_remediation_date", models.DateField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.auditassessment",
                    ),
                ),
                (
                    "ca_remediation_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.status"
                    ),
                ),
                (
                    "identifying_resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.tkresources",
                    ),
                ),
            ],
        ),
    ]
