# Generated by Django 6.0 on 2025-12-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalcontrol",
            name="code",
            field=models.CharField(default="", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
